### PR TITLE
fixes bobi, bobc, fixes broken continue in for()

### PR DESCRIPTION
**Pull request by maarten-boot**
a) bobi/bobi.c and bobc/bobc.c were not fixed the same way as bob/bob.c do they could not compile: fixed

b) using for as in the test.bob example created a endless loop, may have been intentional bot not compatible with expectations and existing behavior in C

c) added a small test in the makefile based on the exiting test.bob but now actually executing, showing the fix of the for/continue

### CODE REVIEW

**Comment by dbetz** [comment]
I'm sorry but I haven't looked at this in years. I'm glad you were able to get it working. I didn't realize that what I checked in didn't build correctly. Sorry

**Comment by maarten-boot** [comment]
no problem, its nice study material,
wanted to do use this for study for a long time ever since i saw the
exetalk and the first bob article in 91
will try to make some test programs as the syntax that was in the older
code files is no more and i see significant changes/improvements
maarten

**Comment by dbetz** [comment]
I'm glad you found it useful. The last time I used it it was in an embedded system where I ran the compiler on a PC and the interpreter on the embedded system. I never used the interactive version.

**Comment by maarten-boot** [comment]
that would be the bob meets Nuon article i guess,
if you happen to have some syntax document or tests i would be obliged.
have a hard time figuring out how the object system works, the examples
from "bob meets nuon", are inclomplete partial snippets

**Comment by dbetz** [comment]
I got rid of the -m32 compile option and the code in GitHub builds fine on the Mac. Unfortunately, it crashes when you run it. I suspect I have a dependency on 32 bit integers that is why I used the -m32 option. That should certainly be fixed. However, I don't really have any use for Bob at this point so I'm not likely to get to this any time soon. Feel free to work on your own branch or create a new repository if you want to develop Bob further. To be honest, there are a million languages like this out there and many are probably under active development. You might be better off with one of those. A lot of people seem to like Lua.

**Comment by dbetz** [comment]
I merged your pull request and I also removed the option to build in 32 bit mode for the Mac since it no longer works with recent versions of Mac OS X. Thanks for your work on this.

**Comment by dbetz** [comment]
So, I thought about this more and I realize that the change I made to disable 32 bit compiles on the Mac doesn't allow the compiler to be used to make binary files that will run on a 32 bit target. If I were going to use this again in an embedded product I would have to make it capable of generating 32 bit binaries even when running on a 64 bit architecture.

**Comment by maarten-boot** [comment]
i moved my copy over to : https://github.com/maarten-boot/bob-mboot
as i favor rigorous formatted code with lots of space in it.
used clion to reformat all and am adding tests to see if i cam make sense
of it.
it compiles and runs in 64 , added #! support to make testing easy
will be playing with it for a while

maarten

**Comment by ghaerr** [comment]
Hello @dbetz and @maarten-boot,

It's nice seeing some interest on this project. Like @maarten-boot, I have followed bob's design and evolution for many years, and have found it a fantastic example of well thought out interpreter design. In particular, the more recent implementation of closures and efficient movement of closed variables from the stack to heap is very well done.

I have made large changes to bob's earlier codebase back in the '90s and '00s, implementing a javascript-like language and lots of extensions to run native code, DLLs (in the day), etc. I found this GitHub repo around a year ago, and have had several ideas for using it as the basis of a language close to javascript with full closures, but not all the problems of javascript. (Thanks David for posting this!!)

Finally, I too am interested in any external documentation or source files @dbetz might have on the current syntax this interpreter supports (rather than learning only through the compiler/interpreter), as well as any test code/suites that might be laying around.

I develop on macOS, so can certainly test the 32/64 bit issues @dbetz mentions above. I also have a large suite of test bob code, as well as the original much-enhanced interpreter/compiler, but the language has changed since then, that's why I'm interested in any source bases of bob code that may be available.

Thank you David for such a great project!

**Comment by dbetz** [comment]
I’m sorry to hear that you reformatted all of the code. That, of course, will make it impossible to incorporate any future changes you make into the original repository. Good luck with your version.

**Comment by maarten-boot** [comment]
no worries i keep a no-formmatted version in paralell for if i want to
contribute back or sync with your code ;-)
this way i can extensivly comment in my code to assist my aging brain

**Comment by maarten-boot** [comment]
figured out the obj system inheritance.
https://github.com/maarten-boot/bob-mboot/blob/main/test/test_obj.bob
will get there eventually ;-)

**Comment by dbetz** [comment]
While I was using it for our Nuon development, people encouraged me to make it as much like Javascript as possible. I think that was actually a mistake and I should probably undo at least some of the changes. One thing that I added that probably slowed down the interpreter is the ability to have a different scope for every HTML-like page. For most uses, a single scope would be sufficient.

**Comment by maarten-boot** [comment]
yes i saw that the class definition from the bob-1.2 and bob-1.5 is now
missing, was wondering about it but as you say expected that it was related
to the Nuon environment.
will be working on a small doc for the syntax and a set of test programs to
show how things work.
will make a pull request when i have some concrete text for that.
m.

**Comment by dbetz** [comment]
I’m beginning to think that what I put in GitHub was not the most recent Nuon version as you had to remove some code that related to line numbers in error messages. I know that was working at VM Labs so there must be some newer source code around somewhere.

**Comment by maarten-boot** [comment]
If you have a newer version somewhere that would be nice if not also ok,
We can see where we go from here,
I also have the 1.2 version and a 1.5 is on internet in stuffit format that
i cannot unpack on modern linux anymore
those would be only for historical interest as is the etalk code

**Pull request merged**
