### PR TITLE
fix switch; add # as comment started for #! support; add tests: all pass

### PR DESCRIPTION
**Pull request by maarten-boot**
switch did not compile with case or break needed frequire(c, '{'); do_block9c);
switch did not create the case context on the stack addswitch(c, ... add at the end c-> ssp = swentry;
to support #! added # as single line comment just like //
added test dir with dome initial functional tests, all compile , all execute

### CODE REVIEW

**Comment by dbetz** [comment]
I merged your pull request but deleted the "forgot" comment. Thanks for adding the single line comments!

**Comment by dbetz** [comment]
I looked around and found another version of the Bob sources that might be closer to what I used at VM Labs. Unfortunately, they are quite a bit different from the sources in GitHub.

[bob.zip](https://github.com/dbetz/bob/files/7946061/bob.zip)

**Comment by maarten-boot** [comment]
Thanks, Will have a look.

**Comment by maarten-boot** [comment]
yes compiled it, looks ok,

lets call the current bob on github bob-2020 (the copy right date on the
licence)
lets call this bob.zip bob-2001 the latest copyright date in most files
(most file dates are 2002 with one change in 2008 on bobcom.c)

bob-2020 will automatically create unbound variables on the fly and use nil
as their value
bob-2001 will throw a runtime error "Error: Unbound variable -" which i is
the better one imho.

so far all tests i made pass including the switch test  if i remove unbound
variables

bob-2001 also makes the compiler and interpreteer dynamically where as the
bob-2020 uses static global variables,
bob-2001 is the better one also imho

perhaps upload this archive as bob-2001 and rename bob to bob-2020 or
remove alltogether

i can assume the same MIT licence can be applied to the zip  (aka
bob-2001)  ?

maarten

**Comment by dbetz** [comment]
Are the bugs that you fixed present in the version in the zip file? If not, I think I'll just tag the current version in GitHub and upload the new version as the official version. I don't want two different versions of Bob on GitHub. And yes, the same MIT license applies.

**Comment by dbetz** [comment]
BTW, you mention that the old Bob uses static global variables but the new one uses dynamically allocated memory. This is because of something I mentioned earlier. The new Bob was used in Nuon where the UI was managed by an HTML-like language and Bob was used as a Javascript substitute. This meant each HTML page needed its own variable scope, hence the dynamic allocation. I might be tempted to remove that feature since it probably slows the interpreter down.

**Comment by maarten-boot** [comment]
yes i see,
the 2001 version does not have that (static interpreter and compiler) and
all tests pass (the switch case bug is not present in the older 2001
version)
so go feel free to tag the current github version and upload the 2001 as
the new current version,
it has the benefit of having doc/bob.doc , you might want to convert that
to txt first or to readme.md

**Comment by dbetz** [comment]
You call the "2001 version" the older version but it is actually newer. I just checked in the wrong version to GitHub and when I did I updated its copyright notices. I was surprised that you found the bugs you did because we used Bob fairly extensively at VM Labs. The explanation is that I checked in an older version by mistake. Sorry about that.

**Comment by maarten-boot** [comment]
no problem, its important to prove every now and then we are human ;-)

i see matrix support was beginning in the 2001 version but not finished,
float support does not compile yet,
perhaps we can find time to fix or remove the matrix and leave the float as
float seems to have worked before.

**Comment by maarten-boot** [comment]
after you have uploaded the 2001 sources i will add the #! support again
and probably add my -d and -v switches for debug and verbose in bob bobc
and bobi as i use that in the tests sometimes
and work a bit more on various tests to show how things work for new
beginners (and myself ;-) )

i noted a wish for a table driven parser in bob1.2 (way back then)
we have lemon now  ( https://sqlite.org/src/doc/trunk/doc/lemon.html )
possibly i find the time to hack a parser based on that as a experiment

**Comment by dbetz** [comment]
I think matrix support should be removed. I can’t recall why I was starting to add it. Float support should, of course, be made to work. I’ll look into that.

**Comment by maarten-boot** [comment]
question: in do_function was it intended to support both IDENTIFIER and
STRING as a optional function name or just IDENTIFIER

{code}
/* do_function - parse a regular definition */
static void do_function(BobCompiler *c, PVAL *pv) {
    char name[256];
    int nameP, tkn;

    /* check for a function name */
    switch (tkn = BobToken(c)) {

        case T_IDENTIFIER:
        case T_STRING:
            strcpy(name, c->t_token);
            nameP = TRUE;
            break;

        default:
            BobSaveToken(c, tkn);
            nameP = FALSE;
            break;
    }

    /* compile function body */
    compile_code(c, nameP ? name : NULL);

    /* store the function as the value of the global symbol */
    // TODO: if (tkn == T_IDENTIFIER | tkn == T_STRING ) {
    // original say: if (tkn == T_IDENTIFIER) {
    if (tkn == T_IDENTIFIER | tkn == T_STRING ) {
        putcbyte(c, BobOpGSET);
        putcword(c, make_lit_symbol(c, name));
    }

    pv->fcn = NULL;
}
{code}

**Comment by maarten-boot** [comment]
tests in :
https://github.com/maarten-boot/bob-mboot/blob/main/test/test_literal.bob

**Comment by maarten-boot** [comment]
after adding a few ifdefs for MATRIX , float is working fine

https://github.com/maarten-boot/bob-mboot/blob/main/test/test_float.bob

**Comment by dbetz** [comment]
I decided against tagging the current bob repository and ended up creating a bob2 repository with the newer code. It turns out that that version builds the executable "bob2" anyway so I guess it's an appropriate name. I just checked it in as-is. I'll go back and remove the matrix stuff and fix the compile warnings later.

**Comment by maarten-boot** [comment]
excelent!

**Comment by dbetz** [comment]
I removed the matrix stuff. I haven’t decided what to do about the compile warnings though. It seems most of them have to do with the fact that I use unsigned char for strings instead of char. I can’t recall why I did that so I’m hesitate to change it.

**Comment by maarten-boot** [comment]
so far all works fine with all the tests i wrote so the warnings seem not
relevant at this time,
i will later re-apply the # comments and make a txt version of Bob.doc
if you are interested we can add my test directory showing how things work
for new adventurers into bob2.
as i read through the code i will make more tests showing how most stuff
works.

**Comment by dbetz** [comment]
Yes, go ahead and add the test directory as well as the # comments. Thanks for your work on this!

**Pull request merged**
